##CREATE SHOP OWNER
POST http://localhost:8080/shops
Content-Type: application/json

{
    "name": "Luxe Locks Beauty",
    "email": "mail@luxe.com",
    "locationName": "Nakuru",
    "location": "google.maps",
    "role": "shops",
    "phone": "254742734120",
    "shopKey": "SHOP3"


}

###
"Radiant Beauty Co.": 63cc26d28a15c8ade516afe1
"Glow by Nature" : 63cc277a3df82e5e47ca867c
"Luxe Locks Beauty": 63cc285f3df82e5e47ca867f

###
##GET ONE, BY ID
GET http://localhost:8080/shops/63cc26d28a15c8ade516afe1

###
##GET ALL
GET http://localhost:8080/shops

###
##UPDATE
PUT http://localhost:8080/shops/63bd19eb6ce3bb964a44c5e8
Content-Type: application/json

{
    "name": "shops2 Update",
    "email": "shops2@pride.com",
    "locationName": "Nairobi",
    "location": "google.maps",
    "role": "shops",
    "phone": "254742734120",
    "shopKey": "shops2"
}
    


###
##DELETE
DELETE http://localhost:8080/shops/63bd19eb6ce3bb964a44c5e8